// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AuthResponse struct {
	AccessToken  string `json:"accessToken"`
	TokenType    string `json:"tokenType"`
	ExpiresIn    int    `json:"expiresIn"`
	RefreshToken string `json:"refreshToken"`
	UserID       string `json:"userId"`
}

type InputLogin struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	GrantType string `json:"grantType"`
}

type InputUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type Token struct {
	UserID       string `json:"userId"`
	CreatedAt    string `json:"createdAt"`
	LastAccessAt string `json:"lastAccessAt"`
	Token        string `json:"token"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Token    string `json:"token"`
}

type UserLogin struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Token    string `json:"token"`
}
